# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.6

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

test-windows:
  tags:
  - windows
  - spiegel-data
  before_script:
  - 'PATH=C:\Users\Alan\Anaconda3\envs\py36;C:\Users\Alan\Anaconda3\envs\py37;%PATH%'
  - where.exe python
  - python -V               # Print out python version for debugging
  - '>>.env echo TESTBASE=F:/Tests/hybridfactory'
  script:
  - pip3 install tox
  - tox -e py36,py37
  coverage: '/TOTAL.+?(\d+)%/'

test-nix:
  tags:
  - nix
  - spiegel-data
  before_script:
  - 'export PATH=/opt/anaconda3/envs/py36/bin:/opt/anaconda3/envs/py37/bin:$PATH'
  - which python
  - python -V               # Print out python version for debugging
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - 'echo TESTBASE=/data/hybridfactory >.env'
  script:
  - pip3 install tox
  - tox -e py36,py37
  coverage: '/TOTAL.+?(\d+)%/'

wheelify:
  script:
  - python3 setup.py sdist bdist_wheel
  artifacts:
    paths:
    - dist/

pages:
  stage: deploy
  tags:
  - nix
  before_script:
  - python3 -V               # Print out python version for debugging
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  script:
  - pip3 install tox
  - tox -e doc
  - mv docs/build/html/ public/
  artifacts:
    paths:
    - public/
  only:
  - master
